plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
}

/**
 * Generates `AppConfig` into `commonMain` -- the replacement for `BuildConfig`.
 *
 * Why generated rather than handwritten: the values are deployment secrets and
 * endpoints that arrive as Gradle properties (and as `ORG_GRADLE_PROJECT_*` in
 * CI), so they cannot be committed. Why generated rather than BuildKonfig: it
 * is ~25 lines with no plugin-compatibility surface against AGP 9, and the
 * values stay compile-time constants, which is what the call sites need.
 *
 * Why it lives here and not in :android:app: AGP 9 does not generate
 * `BuildConfig` for Kotlin Multiplatform library modules, so :app cannot read
 * these once it becomes one. This module is already a KMP library, so
 * `commonMain` is a single, stable source set that accepts a generated srcDir --
 * an application module's per-variant Kotlin source sets do not reliably.
 *
 * Architecturally this is the right home regardless: it is shared configuration,
 * so it belongs in `sharedLogic` where the iOS SwiftUI shell and the desktop app
 * can both read it, not in an Android-only application module.
 */
fun String.escapedForKotlin() = this.replace("\\", "\\\\").replace("\"", "\\\"")

val supabaseUrl = providers.gradleProperty("SUPABASE_URL").orNull.orEmpty()
val supabasePublishableKey =
    providers.gradleProperty("SUPABASE_PUBLISHABLE_KEY").orNull.orEmpty()
val crispyBackendUrl = providers.gradleProperty("CRISPY_BACKEND_URL").orNull.orEmpty()
val introDbApiUrl =
    providers.gradleProperty("INTRODB_API_URL").orNull ?: "https://api.introdb.app"

val generatedConfigDir = layout.buildDirectory.dir("generated/appconfig/kotlin")
val generateAppConfig by tasks.registering {
    val url = supabaseUrl
    val publishableKey = supabasePublishableKey
    val backendUrl = crispyBackendUrl
    val introDb = introDbApiUrl
    // Read from the shared `crispyVersionName` Gradle property, which
    // :androidApp also reads for `defaultConfig.versionName`. One source, so the
    // version the APK reports and the version the app sends to the backend cannot
    // drift -- which is what a hand-kept second copy silently invites.
    //
    // This is the base version and carries no flavour suffix. :androidApp gives the
    // `sideload` flavour a `versionNameSuffix` so the store and sideload APKs can be
    // installed side by side; that suffix is a packaging concern and is deliberately
    // not reported to the backend, which is told `appVersion` and separately
    // `source = "android"`.
    val versionName = providers.gradleProperty("crispyVersionName").get()

    inputs.property("supabaseUrl", url)
    inputs.property("supabasePublishableKey", publishableKey)
    inputs.property("crispyBackendUrl", backendUrl)
    inputs.property("introDbApiUrl", introDb)
    inputs.property("versionName", versionName)
    outputs.dir(generatedConfigDir)

    doLast {
        val dir = generatedConfigDir.get().asFile.resolve("com/crispy/tv/platform")
        dir.mkdirs()
        dir.resolve("AppConfig.kt").writeText(
            """
            |// Generated by :android:platform-core:generateAppConfig. Do not edit.
            |package com.crispy.tv.platform
            |
            |/**
            | * Compile-time configuration shared by every platform.
            | *
            | * Replaces `BuildConfig`, which AGP 9 does not generate for Kotlin
            | * Multiplatform library modules. Field names are identical to the old
            | * `BuildConfig` ones so the call sites are a pure rename.
            | */
            |object AppConfig {
            |    const val SUPABASE_URL: String = "${url.escapedForKotlin()}"
            |    const val SUPABASE_PUBLISHABLE_KEY: String = "${publishableKey.escapedForKotlin()}"
            |    const val CRISPY_BACKEND_URL: String = "${backendUrl.escapedForKotlin()}"
            |    const val INTRODB_API_URL: String = "${introDb.escapedForKotlin()}"
            |    const val VERSION_NAME: String = "${versionName.escapedForKotlin()}"
            |}
            |
            """.trimMargin(),
        )
    }
}

kotlin {
    android {
        namespace = "com.crispy.tv.platform"
        compileSdk = 37
        minSdk = 26

        // This module had no test source set at all, which is why `SecretFormat`
        // -- the encrypted-secret contract that the Android store, the desktop
        // store and any future Apple one all implement -- was pinned by neither.
        // Without this block a `commonTest` directory exists, nothing compiles or
        // runs it on Android, and AGP only *warns*. See the same finding on
        // `:android:addons`, where five Android-shaped files meant nobody created
        // a test source set for the module at all.
        withHostTest {}
    }

    jvm("desktop")

    // Compile-only verification target; see the note in :android:core-domain.
    // It applies the same "no JVM API" rule as the Apple targets and is the
    // one Native target that builds on a Linux host.
    linuxX64()

    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            // The *task provider*, not the directory.
            //
            // An earlier version passed `generatedConfigDir` and carried a comment
            // claiming the KMP source-set API infers the task dependency from the
            // Provider. It does not: `layout.buildDirectory.dir(...)` is a Provider
            // of a path and carries no task information, so nothing ordered
            // `generateAppConfig` before compilation and the task never ran. It
            // worked locally for weeks only because a previous run had left
            // `build/generated/appconfig/.../AppConfig.kt` on disk, so the
            // compiler found a class that nothing in the current build produced.
            //
            // CI has no such residue, so the first run on a clean machine failed
            // with `Unresolved reference 'AppConfig'` across eight files. Passing
            // the TaskProvider registers the task's outputs as the source dir and
            // infers the dependency, which is why `srcDir(taskProvider)` is the
            // idiom everywhere else in this build.
            kotlin.srcDir(generateAppConfig)
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

