package com.crispy.tv.backend

/**
 * A [BackendApi] that implements nothing, so a test can hand one to a consumer
 * without stubbing 51 methods it will never call.
 *
 * [BackendContextResolver] reads exactly one member of this interface:
 * [isConfigured]. The other 51 exist so this class keeps compiling as a complete
 * implementation -- which is the point. A partial double that quietly stopped
 * implementing [BackendApi] would let a new interface member ship with no test
 * noticing; because these are real `override`s, adding one to the interface
 * breaks this file instead. The compiler is the exhaustiveness check here, the
 * same way it is for `CrispyBackendClient`.
 *
 * The bodies throw rather than return a default. A member the test did not
 * expect to be called should fail loudly; returning `null` or `0` would let it
 * pass and hide the fact that a call path changed.
 *
 * Generated by copying the signatures out of `BackendApi.kt`, then checked by the
 * compiler -- the same narrow-with-a-script, judge-with-the-compiler split the
 * `BackendApi` port itself used.
 */
internal class UnusedBackendApi(
    private val configured: Boolean = true,
) : BackendApi {

    override val baseUrl: String get() = unused("baseUrl")

    override fun isConfigured(): Boolean = configured

    override suspend fun getMe(accessToken: String): Nothing = unused("getMe")
    override suspend fun createProfile(
                                       accessToken: String,
                                       name: String,
                                       sortOrder: Int?,
                                       isKids: Boolean,
                                       avatarKey: String?,
                                       interfaceLanguage: String?
    ): Nothing = unused("createProfile")
    override suspend fun bootstrapAccount(
                                          accessToken: String,
                                          name: String,
                                          interfaceLanguage: String,
                                          avatarUrl: String,
                                          region: String?
    ): Nothing = unused("bootstrapAccount")
    override suspend fun listImportConnections(
                                               accessToken: String,
                                               profileId: String
    ): Nothing = unused("listImportConnections")
    override suspend fun listImportJobs(accessToken: String, profileId: String): Nothing = unused("listImportJobs")
    override suspend fun disconnectImportConnection(
                                                    accessToken: String,
                                                    profileId: String,
                                                    provider: ImportProvider
    ): Nothing = unused("disconnectImportConnection")
    override suspend fun startImport(
                                     accessToken: String,
                                     profileId: String,
                                     provider: ImportProvider,
                                     action: String,
                                     clientId: String,
                                     returnTo: String
    ): Nothing = unused("startImport")
    override suspend fun getProfileSettings(
                                            accessToken: String,
                                            profileId: String
    ): Nothing = unused("getProfileSettings")
    override suspend fun patchProfileSettings(
                                              accessToken: String,
                                              profileId: String,
                                              settings: Map<String, String>
    ): Nothing = unused("patchProfileSettings")
    override suspend fun listProfiles(accessToken: String): Nothing = unused("listProfiles")
    override suspend fun updateProfile(
                                       accessToken: String,
                                       profileId: String,
                                       input: UpdateProfileInput
    ): Nothing = unused("updateProfile")
    override suspend fun getAccountSettings(accessToken: String): Nothing = unused("getAccountSettings")
    override suspend fun patchAccountSettings(
                                              accessToken: String,
                                              settings: Map<String, String>
    ): Nothing = unused("patchAccountSettings")
    override suspend fun deleteAccount(accessToken: String): Nothing = unused("deleteAccount")
    override suspend fun listAddons(accessToken: String): Nothing = unused("listAddons")
    override suspend fun installAddon(
                                      accessToken: String,
                                      profileId: String,
                                      manifestUrl: String,
                                      type: String,
                                      payload: Map<String, String>
    ): Nothing = unused("installAddon")
    override suspend fun uninstallAddon(
                                        accessToken: String,
                                        profileId: String,
                                        addonId: String
    ): Nothing = unused("uninstallAddon")
    override suspend fun getAvatars(): Nothing = unused("getAvatars")
    override suspend fun searchTitles(accessToken: String, query: String, limit: Int): Nothing = unused("searchTitles")
    override suspend fun searchSuggestions(
                                           accessToken: String,
                                           query: String,
                                           limit: Int
    ): Nothing = unused("searchSuggestions")
    override suspend fun searchTitlesByGenre(
                                             accessToken: String,
                                             genre: String,
                                             limit: Int
    ): Nothing = unused("searchTitlesByGenre")
    override suspend fun searchAiTitles(
                                        accessToken: String,
                                        profileId: String,
                                        query: String,
                                        locale: String?
    ): Nothing = unused("searchAiTitles")
    override suspend fun getAiInsights(
                                       accessToken: String,
                                       profileId: String,
                                       itemId: String,
                                       locale: String?
    ): Nothing = unused("getAiInsights")
    override suspend fun getMetadataItemDetail(
                                               accessToken: String,
                                               itemId: String
    ): Nothing = unused("getMetadataItemDetail")
    override suspend fun getMetadataItemExtras(
                                               accessToken: String,
                                               itemId: String
    ): Nothing = unused("getMetadataItemExtras")
    override suspend fun getSeriesEpisodes(
                                           accessToken: String,
                                           seriesItemId: String,
                                           season: Int?
    ): Nothing = unused("getSeriesEpisodes")
    override suspend fun getMetadataItemRatings(
                                                accessToken: String,
                                                profileId: String,
                                                itemId: String
    ): Nothing = unused("getMetadataItemRatings")
    override suspend fun getMetadataPersonDetail(
                                                 accessToken: String,
                                                 personId: String,
                                                 language: String?
    ): Nothing = unused("getMetadataPersonDetail")
    override suspend fun browseTitles(
                                      accessToken: String,
                                      type: String,
                                      genre: String?,
                                      sort: String,
                                      page: Int
    ): Nothing = unused("browseTitles")
    override suspend fun getHome(accessToken: String, profileId: String): Nothing = unused("getHome")
    override suspend fun getCalendar(accessToken: String, profileId: String): Nothing = unused("getCalendar")
    override suspend fun getCalendarThisWeek(
                                             accessToken: String,
                                             profileId: String
    ): Nothing = unused("getCalendarThisWeek")
    override suspend fun getUpNext(accessToken: String, profileId: String, limit: Int): Nothing = unused("getUpNext")
    override suspend fun resolvePlayback(
                                         accessToken: String,
                                         input: ItemLookupInput
    ): Nothing = unused("resolvePlayback")
    override suspend fun sendWatchEvent(
                                        accessToken: String,
                                        profileId: String,
                                        input: PlaybackEventInput
    ): Nothing = unused("sendWatchEvent")
    override suspend fun listContinueWatching(
                                              accessToken: String,
                                              profileId: String,
                                              limit: Int,
                                              cursor: String?
    ): Nothing = unused("listContinueWatching")
    override suspend fun dismissContinueWatching(
                                                 accessToken: String,
                                                 profileId: String,
                                                 itemId: String
    ): Nothing = unused("dismissContinueWatching")
    override suspend fun listWatchHistory(
                                          accessToken: String,
                                          profileId: String,
                                          limit: Int,
                                          cursor: String?
    ): Nothing = unused("listWatchHistory")
    override suspend fun listWatchlist(
                                       accessToken: String,
                                       profileId: String,
                                       limit: Int,
                                       cursor: String?
    ): Nothing = unused("listWatchlist")
    override suspend fun listRatings(
                                     accessToken: String,
                                     profileId: String,
                                     limit: Int,
                                     cursor: String?
    ): Nothing = unused("listRatings")
    override suspend fun getWatchGenerations(
                                             accessToken: String,
                                             profileId: String
    ): Nothing = unused("getWatchGenerations")
    override suspend fun getWatchState(
                                       accessToken: String,
                                       profileId: String,
                                       itemId: String
    ): Nothing = unused("getWatchState")
    override suspend fun getWatchStates(
                                        accessToken: String,
                                        profileId: String,
                                        itemIds: List<String>
    ): Nothing = unused("getWatchStates")
    override suspend fun getWatchStateMap(
                                          accessToken: String,
                                          profileId: String,
                                          itemIds: List<String>
    ): Nothing = unused("getWatchStateMap")
    override suspend fun markWatched(
                                     accessToken: String,
                                     profileId: String,
                                     input: WatchMutationInput
    ): Nothing = unused("markWatched")
    override suspend fun unmarkWatched(
                                       accessToken: String,
                                       profileId: String,
                                       input: WatchMutationInput
    ): Nothing = unused("unmarkWatched")
    override suspend fun putWatchlist(
                                      accessToken: String,
                                      profileId: String,
                                      itemId: String,
                                      occurredAt: String?,
                                      payload: Map<String, Any?>
    ): Nothing = unused("putWatchlist")
    override suspend fun deleteWatchlist(
                                         accessToken: String,
                                         profileId: String,
                                         itemId: String
    ): Nothing = unused("deleteWatchlist")
    override suspend fun setLiked(
                                  accessToken: String,
                                  profileId: String,
                                  itemId: String,
                                  liked: Boolean,
                                  occurredAt: String?,
                                  payload: Map<String, Any?>
    ): Nothing = unused("setLiked")
    override suspend fun deleteRating(
                                      accessToken: String,
                                      profileId: String,
                                      itemId: String
    ): Nothing = unused("deleteRating")

    private fun unused(name: String): Nothing =
        error("BackendApi.$name was called by a test that does not stub it.")
}
