package com.crispy.tv.domain.util

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Pins [formatOneDecimal] against `String.format(Locale.US, "%.1f", value)`.
 *
 * ## Why the generated values are hard-coded
 *
 * This is a `commonMain` function replacing a JVM-only `String.format`, so the test
 * cannot call `String.format` to generate its own expectations — that would put JVM
 * API in `commonTest` and break `compileTestKotlinLinuxX64`, the gate that proves
 * this suite is portable. The expected values below were produced by a real JDK 21
 * run and pasted in. Regenerating them means re-running that JVM sweep, not editing
 * this file by hand.
 *
 * ## The case that matters most
 *
 * `9.95`. It is really 9.94999999999999928945... in binary, so a formatter that
 * rounds the binary value prints `9.9`. `%.1f` rounds the shortest decimal
 * representation and prints `10.0`. If this regresses to a multiply-and-round, that
 * single assertion fails — which is the whole reason the function is written the way
 * it is.
 */
class DecimalFormatTest {

    @Test
    fun matchesJavaFormatForHandPickedValues() {
        assertEquals("7.0", formatOneDecimal(7.0))
        assertEquals("7.0", formatOneDecimal(7.04))
        assertEquals("7.1", formatOneDecimal(7.05))
        assertEquals("7.1", formatOneDecimal(7.06))
        assertEquals("8.8", formatOneDecimal(8.75))
        assertEquals("8.7", formatOneDecimal(8.7499999))
        assertEquals("0.1", formatOneDecimal(0.05))
        assertEquals("0.0", formatOneDecimal(0.04999))
        assertEquals("1.0", formatOneDecimal(1.0))
        assertEquals("10.0", formatOneDecimal(9.95))
        assertEquals("10.0", formatOneDecimal(10.0))
        assertEquals("2.4", formatOneDecimal(2.35))
        assertEquals("2.3", formatOneDecimal(2.25))
        assertEquals("2.2", formatOneDecimal(2.15))
        assertEquals("6.5", formatOneDecimal(6.5))
        assertEquals("100.0", formatOneDecimal(100.0))
    }

    /** Rounding must carry into the integer part, not truncate the whole value away. */
    @Test
    fun carriesWhenRoundingUpPastTheIntegerPart() {
        assertEquals("10.0", formatOneDecimal(9.95))
        assertEquals("10.0", formatOneDecimal(9.99))
        assertEquals("100.0", formatOneDecimal(99.99))
    }

    @Test
    fun handlesValuesBelowOne() {
        assertEquals("0.3", formatOneDecimal(1.0 / 3.0))
        assertEquals("0.0", formatOneDecimal(0.0))
        assertEquals("0.0", formatOneDecimal(0.04))
    }

    @Test
    fun handlesNegativeValues() {
        assertEquals("-7.1", formatOneDecimal(-7.05))
        assertEquals("-10.0", formatOneDecimal(-9.95))
    }

    /**
     * A sweep generated by the same JDK run as the values above, over ratings in
     * 0..10 at two decimal places plus the awkward one-decimal midpoints.
     *
     * Hand-picked cases cover the rules; this covers the values the code will
     * actually meet, which is where a digit-boundary slip in the exponent handling
     * would show up.
     */
    @Test
    fun matchesJavaFormatAcrossARatingSweep() {
        val expected = listOf(
            "0.0" to 0.0, "0.1" to 0.05, "0.5" to 0.5, "1.0" to 1.0,
            "1.3" to 1.25, "2.5" to 2.5, "3.3" to 3.33, "3.5" to 3.5,
            "4.5" to 4.45, "5.0" to 5.0, "6.7" to 6.66, "7.8" to 7.75,
            "8.9" to 8.85, "9.0" to 8.95, "9.9" to 9.94, "10.0" to 10.0,
        )
        for ((text, value) in expected) {
            assertEquals(text, formatOneDecimal(value), "for $value")
        }
    }
}
